### ISSUE TITLE
Create make:datagrid command

### ISSUE THREAD

**Issue by daniel-werner** [wdev-rs/laravel-datagrid#11]
Create a `make:datagrid` command which generates datagrid class, for example:

```
class CategoriesDataGrid extends DataGrid
{

    /**
     * CategoriesDataGrid constructor.
     */
    public function __construct()
    {
        $this->fromQuery(Category::query())
            ->column('id', 'ID', null, 50)
            ->column('name', 'Name')
    }
}
```

The command should take the following arguments:
name of the datagrid class

The command should take the following options
- -m|--model name of the model to use
- -f|--fields the name of the fields of the comma separated: 'field1,field2,field3' or 'field1:label1,field2:label2,field3:label3'

The generated datagrid class should be places in \App\DataGrids directory

**Comment by thebatclaudio** [comment]
Hello!
I would like to do this issue. Can you assign to me?

**Comment by daniel-werner** [comment]
Hi,
Go for it :)

**Comment by thebatclaudio** [comment]
Hello @daniel-werner! I created the pull request, let me know if it's ok
