### ISSUE TITLE
Update for Vue 3

### ISSUE THREAD

**Issue by mrsnax** [wdev-rs/laravel-datagrid#21]
Hello, can you update this script for Vue 3?

Thanks

**Comment by daniel-werner** [comment]
Hi @mrsnax, 

Vue 3 and vite support, is in progress. I plan to release the 1.0 version in the next 1-2 weeks, and it is going to have support for vue3 and vite, also should remove some dependencies, and have a choice of 2 frontend options.

**Comment by daniel-werner** [comment]
@mrsnax DataGrid 1.0.0 was released with Vue3 support, and 2 frontend options! 🎉
