### ISSUE TITLE
Unable to pass additional data to render method

### ISSUE THREAD

**Issue by Wonderstruck80** [wdev-rs/laravel-datagrid#25]
I need to pass additional data (for a dropdown filter) from controller to render method and to blade template but I do not see a way to accomplish that without overriding the DataGrid.php file.  I thought I could just override the render method in the class which extends Datagrid but getData (called within render) is marked as private.

**Comment by daniel-werner** [comment]
@Wonderstruck80 I made the the getData protected in v 1.0.1, so now you can overwrite the render method to pass additional data to view

**Comment by Wonderstruck80** [comment]
That simplifies things thank you very much!
