### ISSUE TITLE
How to use a plain array as source

### ISSUE THREAD

**Issue by lsblsb** [wdev-rs/laravel-datagrid#3]
I fetch data from a SOAP interface and want to use its result (array or Collection) as data source.
Is that intended at all, and how can i do it?

**Comment by daniel-werner** [comment]
Hey @lsblsb, 
It is a great idea, I'll add it to the project roadmap. Hopefully I'll find time to do it soon, but every contribution is welcome :)

**Comment by daniel-werner** [comment]
In the version 0.3.0 you can use array or Collection as a data source. (use the fromCollection or fromArray methods). @lsblsb
